/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_digitalsquid_internetrestore_jni_WpaControl */

#ifndef _Included_uk_digitalsquid_internetrestore_jni_WpaControl
#define _Included_uk_digitalsquid_internetrestore_jni_WpaControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_digitalsquid_internetrestore_jni_WpaControl
 * Method:    openCtrl
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_digitalsquid_internetrestore_jni_WpaControl_openCtrl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uk_digitalsquid_internetrestore_jni_WpaControl
 * Method:    closeCtrl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_uk_digitalsquid_internetrestore_jni_WpaControl_closeCtrl
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
