/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_digitalsquid_internetrestore_jni_WpaControl_WpaMessage */

#ifndef _Included_uk_digitalsquid_internetrestore_jni_WpaControl_WpaMessage
#define _Included_uk_digitalsquid_internetrestore_jni_WpaControl_WpaMessage
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
