/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_digitalsquid_internetrestore_jni_FileUtil */

#ifndef _Included_uk_digitalsquid_internetrestore_jni_FileUtil
#define _Included_uk_digitalsquid_internetrestore_jni_FileUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_digitalsquid_internetrestore_jni_FileUtil
 * Method:    setExecutable
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_digitalsquid_internetrestore_jni_FileUtil_setExecutable
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uk_digitalsquid_internetrestore_jni_FileUtil
 * Method:    setPublicVisible
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_uk_digitalsquid_internetrestore_jni_FileUtil_setPublicVisible
  (JNIEnv *, jclass, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
